# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for a detailed guide
name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit
          python -m flit install --symlink

      - name: Build
        run: python -m flit build

      - name: Publish to PyPI
        env:
          FLIT_USERNAME: '__token__'
          FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          FLIT_INDEX_URL: https://upload.pypi.org/legacy/
        run: python -m flit publish
